# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fed87119cd8f42d99f01c0c492a39d7ea014855b3c01dff3afb134c493d27e8ec5e1111e2752d67e281acde66f4b4112c178476abe612609646812359eab994c

test:
  secret_key_base: bfc658af50120298d34cfdf8ac904e887fc75718c7bda8efc002c4a0471aa8802dccf82b2ab34dd8275dceaa3199f4496e7f90d305ec8aa3a52c4ceec28df33c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
