# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03cb5e56ca1ce3ceadd89cba55bbefa07921e5fff17969b5ffaf0b63f725fc12d8e942821984e5886b7043c9c87df87c093527c1f50b617927114635b248d52b

test:
  secret_key_base: 5b34734b4fe595597bfe7779a704fb453a07056e7f7bd172074066cbdecbeb6dc1704b5f16d4c84e8210b5cbd9142d2af664ee64bad9733367da7432a18937ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
